insert into pr2.MechFault (mFaultID, descript, mPartNum, equipID) values (1, 'Proin risus.', 81013, 4);
insert into pr2.MechFault (mFaultID, descript, mPartNum, equipID) values (2, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 77256, 4);
insert into pr2.MechFault (mFaultID, descript, mPartNum, equipID) values (3, 'Praesent blandit lacinia erat.', 75840, 15);
insert into pr2.MechFault (mFaultID, descript, mPartNum, equipID) values (4, 'Mauris lacinia sapien quis libero.', 66011, 7);
insert into pr2.MechFault (mFaultID, descript, mPartNum, equipID) values (5, 'In blandit ultrices enim.', 11598, 18);
insert into pr2.MechFault (mFaultID, descript, mPartNum, equipID) values (6, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 55176, 18);
insert into pr2.MechFault (mFaultID, descript, mPartNum, equipID) values (7, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 52688, 15);
insert into pr2.MechFault (mFaultID, descript, mPartNum, equipID) values (8, 'Nullam porttitor lacus at turpis.', 59339, 19);
insert into pr2.MechFault (mFaultID, descript, mPartNum, equipID) values (9, 'Ut at dolor quis odio consequat varius.', 45086, 7);
insert into pr2.MechFault (mFaultID, descript, mPartNum, equipID) values (10, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 49372, 14);
